# Production environment configuration for Firebase App Hosting
# This file overrides values from .apphosting.yaml
# See: https://firebase.google.com/docs/app-hosting/multiple-environments

runConfig:
  runtime: nodejs20
  # Production: More resources for better performance
  cpu: 2
  memoryMiB: 2048
  maxInstances: 10
  minInstances: 1
  concurrency: 100

env:
  # Production environment variables
  - variable: NODE_ENV
    value: production
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_TELEMETRY_DISABLED
    value: "1"
    availability:
      - BUILD
      - RUNTIME

  # Production URLs
  - variable: NEXT_PUBLIC_BASE_URL
    value: https://palkamtm.pl
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXTAUTH_URL
    value: https://palkamtm.pl
    availability:
      - RUNTIME

  # Database - Supabase PostgreSQL
  # Dla runtime używamy PgBouncer (port 6543) - lepsze dla serverless
  - variable: DATABASE_URL
    value: postgresql://postgres:Milosz%2E1205@db.fodfctgqzcuhqwcpupni.supabase.co:6543/postgres?pgbouncer=true&connection_limit=1
    availability:
      - RUNTIME

  # NextAuth Secret - wygenerowany secret
  - variable: NEXTAUTH_SECRET
    value: wByeVufjYdavIMUhPsntG/CA0H6MvplAb6T/db6yf8U=
    availability:
      - RUNTIME

  # Firebase Client-side (TYLKO do autoryzacji - rejestracja, weryfikacja email, SMS)
  # Projekt: pigeon-4fba2
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: AIzaSyD4PcLWRdE61ogbkm1199rV_p-sODJvtuE
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: pigeon-4fba2.firebaseapp.com
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: pigeon-4fba2
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: pigeon-4fba2.firebasestorage.app
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "1036150984520"
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: 1:1036150984520:web:62445751bd607f2b56ad7d
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    value: G-CDS9QF0ZJH
    availability:
      - BUILD
      - RUNTIME

  # Firebase Admin SDK (Server-side - tylko do autoryzacji SMS)
  - variable: FIREBASE_PROJECT_ID
    value: pigeon-4fba2
    availability:
      - RUNTIME

  - variable: FIREBASE_CLIENT_EMAIL
    value: firebase-adminsdk-xxxxx@pigeon-4fba2.iam.gserviceaccount.com
    availability:
      - RUNTIME

  - variable: FIREBASE_PRIVATE_KEY
    value: "-----BEGIN PRIVATE KEY-----\n[WSTAW_TUTAJ_PRIVATE_KEY_Z_PROJEKTU_pigeon-4fba2]\n-----END PRIVATE KEY-----\n"
    availability:
      - RUNTIME

  # SMS Provider
  - variable: SMS_PROVIDER
    value: firebase
    availability:
      - RUNTIME

buildConfig:
  commands:
    - npm ci
    - npm run build
  env:
    - variable: NODE_ENV
      value: production
    - variable: NEXT_TELEMETRY_DISABLED
      value: "1"
    # Database URL dla build (używamy bezpośredniego połączenia dla migracji Prisma)
    - variable: DATABASE_URL
      value: postgresql://postgres:Milosz%2E1205@db.fodfctgqzcuhqwcpupni.supabase.co:5432/postgres

