# PowerShell script to set up all Vercel environment variables

Write-Host "Setting up Vercel environment variables..."

# Firebase Client-side variables (tylko do rejestracji, weryfikacji email i autoryzacji SMS)
$env:NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyD4PcLWRdE61ogbkm1199rV_p-sODJvtuE"
$env:NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "pigeon-4fba2.firebaseapp.com"
$env:NEXT_PUBLIC_FIREBASE_PROJECT_ID = "pigeon-4fba2"
$env:NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "pigeon-4fba2.firebasestorage.app"
$env:NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1036150984520"
$env:NEXT_PUBLIC_FIREBASE_APP_ID = "1:1036150984520:web:62445751bd607f2b56ad7d"
$env:NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-CDS9QF0ZJH"

# Firebase Server-side variables
$env:FIREBASE_PROJECT_ID = "m-t-m-62972"
$env:FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@m-t-m-62972.iam.gserviceaccount.com"
$env:FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCcRe0BslSnISuR\nFcisDVbgkNvz3jekt/z9KI6LsR4ddyBfyH2up0BcEvLuNXwUTsTKxmTSbn1HoG7m\nnzDIJrzwL0xLBhzujhAbCfPg0nHYqifiVu0QY27nGh+2MltN9q99rDcdVQfVDSsj\nXwiD1py2oX1l5o6PeKsifenacG5tATcexfjnPuxxLdTFyF1LhgMwVNyoPKOvpEsd\nbGG8pWtAXW5xiyJTvHcYI5T0I8oLugNCKYazEWbD0Cz5ZCWUDFuo7jHitU+PYhvN\nsvEiDMySOhmjvdHqR+JvvcBxOnS9241KjTbeZ1adaFLg1E+FxQVfBOkJuJQY4ylX\nvHSrXss9AgMBAAECggEAQfUtlJK9MhFI/yKPoTa8HWpmu6ZmG+rgJ8XPbFxkVpFq\nI6NOkMHc4z/IMwx2A2g/nUphUYP68plfVY2JHGFlS4bbD6tT2MgzOgZYXeLU1Fr1\nHI4N3uXo8DfRfKgCa4ScC1H9rS6vcJfvRi2dPW/+kwLUF4dZUmre6F72rhDYOr8o\nhEQW3LAAgBdm40xWJo8gIRKKtGM7xl0o2CCrilt7XY0DqZrZVnYrNOrphCCt7e4g\nhkhzhDnL5P5Q6B4Vc0kY2xg3/c9Hb5QnBHzMV/N7d6rl3zMrQ7t9B7R8s0BudKRH\n5qtnBr3VjMzYolmpDAp626r55MjPqG2IWdBoSANRzQKBgQDSQCeKegcfM+g2UIOL\nPDwae4PR3BRTOdyvGMcv+lxeXXXE/b2ostiaKKimTKHtRCizozFz7v3gR6MHCCtP\nZqPh3Hya5r0HpslSN2j028wKi2Zj144tWCzyHjArZOsUBXJrh3b/RLrVhobOggDs\nMS4JJUDh+PAM5isX6B+V4Bf6HwKBgQC+Rv/Wi+F4XvhQG9rnOgZ7Cwdx0IRhb/Mi\nIzpeOCC9D/3HeDQHfnwjGJugNZiXibdv4TmjDYxPXWIiK+hQTT1rrt+jm5F3Qgyg\nJ/tBaTEc/eSDFsx9oIIWPk6sQKeUbUXDjCyzPpj7oxIS1FLE1WnJBFH3BQ9hLT9i\n24I72SdHIwKBgQDDA+apNw6sDoVw+7VHzJMjLTXTzgK8P4tGjgETq3FJxf6avZDR\njTIDq3ri5Wm8nd/y34fbNO4evdOljho+B8IymUSqmSL0metaazLbC5Ryo2JRcXra\n7FKkMQQU/AJgC71Zp8jkdWem7qTTnxoj+mns6bUI5NIj5MpL3m6NodIbmQKBgQC4\nccp+BopBTI4X2WiQy8aMb1yAD0jDyuk8JjnmKzJRErdGLFcDDLD4tFnnKw0HmA+g\n/AoK7I8eP79osHc5oCXxxEo1JhAUMopalWcROQ7Ks7JXADqpbHWtaiiJAQNw9Zuy\nuqZ5+iwBgUl7xyWUd+tbWDy73sPRxzKyeWX87bsNUQKBgEuRLuP3I2yJP1GzDClB\n3a0bc19XuXaGmxn0LBzHfqiqkq6lymWUIlFH5r+jibP9dDyvSHE9GWCkmVdfVhAf\nZUhXKc+ChCX0EWEb90+LhpIIY2pMZGg4gVn6NAW/xV3pyueGdDm1ciBPisrqWHMj\nJkH3fKiQfGi52ouES8nVl/tL\n-----END PRIVATE KEY-----\n"

# Other required variables
$env:NEXTAUTH_URL = "https://pigeon-gj4ougkim-marcins-projects-59088b6e.vercel.app"
$env:NEXTAUTH_SECRET = "Uv3thpAmgL98eBwLt0WrL6nIVPSNt+eHHrotyvaqT8E="
$env:NODE_ENV = "production"

Write-Host "Environment variables prepared. Now run the following commands manually:"
Write-Host ""
# Database - użyj zmiennej środowiskowej Vercel (SKŁADOWANIE_URL zostanie automatycznie utworzona przez Vercel)
Write-Host "# UWAGA: Po połączeniu bazy danych w Vercel, zmienna SKŁADOWANIE_URL zostanie automatycznie utworzona"
Write-Host "# Nie musisz ręcznie dodawać DATABASE_URL - użyj SKŁADOWANIE_URL"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_API_KEY --prod"
Write-Host "(Enter: AIzaSyD4PcLWRdE61ogbkm1199rV_p-sODJvtuE)"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN --prod"
Write-Host "(Enter: pigeon-4fba2.firebaseapp.com)"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_PROJECT_ID --prod"
Write-Host "(Enter: pigeon-4fba2)"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET --prod"
Write-Host "(Enter: pigeon-4fba2.firebasestorage.app)"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID --prod"
Write-Host "(Enter: 1036150984520)"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_APP_ID --prod"
Write-Host "(Enter: 1:1036150984520:web:62445751bd607f2b56ad7d)"
Write-Host ""
Write-Host "vercel env add NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID --prod"
Write-Host "(Enter: G-CDS9QF0ZJH)"
Write-Host ""
Write-Host "vercel env add FIREBASE_PROJECT_ID --prod"
Write-Host "(Enter: m-t-m-62972)"
Write-Host ""
Write-Host "vercel env add FIREBASE_CLIENT_EMAIL --prod"
Write-Host "(Enter: firebase-adminsdk-fbsvc@m-t-m-62972.iam.gserviceaccount.com)"
Write-Host ""
Write-Host "vercel env add FIREBASE_PRIVATE_KEY --prod"
Write-Host "(Enter the full private key from above)"
Write-Host ""
Write-Host "vercel env add NEXTAUTH_URL --prod"
Write-Host "(Enter: https://pigeon-gj4ougkim-marcins-projects-59088b6e.vercel.app)"
Write-Host ""
Write-Host "vercel env add NEXTAUTH_SECRET --prod"
Write-Host "(Enter: Uv3thpAmgL98eBwLt0WrL6nIVPSNt+eHHrotyvaqT8E=)"
Write-Host ""
Write-Host "vercel env add NODE_ENV --prod"
Write-Host "(Enter: production)"
Write-Host ""
Write-Host "After setting all variables, run: vercel --prod"
